networks:
  local-kafka:
    driver: bridge

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    networks:
      - local-kafka
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
#    deploy:
#      resources:
#        limits:
#          memory: 450M

  broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    networks:
      - local-kafka
    ports:
      # To learn about configuring Kafka for access across networks see
      # https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/
      - "9092:9092"
      - "9093:9093"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LISTENERS: PLAINTEXT_INTERNAL://0.0.0.0:29092,PLAINTEXT_C://0.0.0.0:9093,PLAINTEXT_L://0.0.0.0:9092,
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_INTERNAL://broker:29092,PLAINTEXT_L://localhost:9092,PLAINTEXT_C://broker:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT_INTERNAL:PLAINTEXT,PLAINTEXT_L:PLAINTEXT,PLAINTEXT_C:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
#    deploy:
#      resources:
#        limits:
#          memory: 450M

#  kafka-ui:
#    image: provectuslabs/kafka-ui
#    container_name: kafka-ui
#    networks:
#      - local-kafka
#    depends_on:
#      - broker
#    ports:
#      - "7777:8080"
#    restart: always
#    environment:
#      - KAFKA_CLUSTERS_0_NAME=broker
#      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=broker:9093
#      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181

  elasticsearch:
    image: bitnami/elasticsearch:8
    platform: linux/arm64
    environment:
      - discovery.type=single-node
#      - ELASTICSEARCH_HEAP_SIZE=512m
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test: ["CMD", "curl", "-s", "http://localhost:9200"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - elasticsearch-data:/bitnami/elasticsearch/data
#    networks:
#      - local-kafka
    deploy:
      resources:
        limits:
          memory: 2g

#  redis:
#    image: redis:7.0
#    container_name: redis
#    ports:
#      - "6379:6379"
#    networks:
#      - local-kafka
volumes:
  elasticsearch-data:
    driver: local